# Generated by Django 4.1.7 on 2023-05-04 16:34

from django.db import migrations, models
import dojo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0188_finding_senario_alter_child_rule_match_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='senario',
            field=models.FileField(blank=True, null=True, upload_to=dojo.models.UniqueUploadNameProvider('uploaded_files')),
        ),
    ]
