# Generated by Django 4.1.7 on 2023-05-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0192_remove_finding_senario_alter_child_rule_match_field_and_more'),
    ]

    operations = []
