# Generated by Django 4.1.7 on 2023-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0193_drop_old_senario_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='complexite',
            field=models.CharField(blank=True, help_text='complexite', max_length=511, null=True, verbose_name='complexite'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='priorite',
            field=models.CharField(blank=True, help_text='priorite', max_length=511, null=True, verbose_name='priorite'),
        ),
    ]
