# Generated by Django 4.1.7 on 2023-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0196_finding_scenarioderisque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='scenarioDeRisque',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
