# Generated by Django 4.1.7 on 2023-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0197_alter_finding_scenarioderisque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='scenarioDeRisque',
            field=models.ImageField(blank=True, null=True, upload_to='senario/'),
        ),
    ]
