# Generated by Django 4.1.7 on 2023-05-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0198_alter_finding_scenarioderisque'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploaded_files/')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dojo.finding')),
            ],
        ),
    ]
