# Generated by Django 4.1.7 on 2023-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0202_alter_findingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='consequences',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='mesures_impactees',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='niveau_securite_global',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='risques',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
