# Generated by Django 4.1.7 on 2023-05-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0204_engagement_compteur'),
    ]

    operations = [
      
    ]
