# Generated by Django 4.1.7 on 2023-05-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0206_engagement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='compteur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
