# Generated by Django 4.1.7 on 2023-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0207_alter_engagement_compteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
