# Generated by Django 4.1.7 on 2023-05-17 15:01

from django.db import migrations, models
import dojo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0208_product_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='scenarioDeRisque',
            field=models.FileField(blank=True, null=True, upload_to=dojo.models.UniqueUploadNameProvider('uploaded_files')),
        ),
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=dojo.models.UniqueUploadNameProvider('uploaded_files')),
        ),
    ]
