# Generated by Django 4.1.7 on 2023-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0209_alter_finding_scenarioderisque_alter_product_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='cibles',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
