# Generated by Django 4.1.7 on 2023-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0210_engagement_cibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
